export const NseDerivativesIndexList = [
  {
    exch: 'NSE',
    token: '26000',
    tsym: 'Nifty 50',
    nontrd: '1',
    pp: '2',
    ls: '1',
    ti: '0.05',
    instname: 'UNDIND',
    cname: 'NIFTY INDEX',
    zname: 'NIFTY',
  },
  {
    exch: 'NSE',
    token: '26009',
    tsym: 'Nifty Bank',
    nontrd: '1',
    pp: '2',
    ls: '1',
    ti: '0.05',
    instname: 'UNDIND',
    cname: 'NIFTY BANK',
    zname: 'BANKNIFTY',
  },
  {
    exch: 'NSE',
    token: '26037',
    tsym: 'Nifty Fin',
    nontrd: '1',
    pp: '2',
    ls: '1',
    ti: '0.05',
    instname: 'UNDIND',
    cname: 'Nifty Fin',
    zname: 'FINNIFTY'
  },
];
